"use strict";
const $=id=>document.getElementById(id);
let state={}, active=null;
const fields=["endpoint","passage","format","reference_text","quote_reference_text","quote_mode","delivery","steps","guidance","speed","instruct","denoise","mastering","spectral_matching","normalize_text","verification","take","timeout","pronunciation","directions"];
const numeric=new Set(["steps","guidance","speed","take","timeout"]);
async function api(path,data){const r=await fetch(path,data===undefined?{}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const body=await r.json();if(!r.ok)throw Error(body.error||"Request failed");return body}
function message(text,ok=false){$("message").textContent=text;$("message").className=ok?"success":""}
function collect(){const c={reference:state.reference||"",quote_reference:state.quote_reference||""};for(const key of fields){const el=$(key);c[key]=el.type==="checkbox"?el.checked:numeric.has(key)?Number(el.value):el.value}return c}
function update(){const text=$("passage").value.trim();$("wordCount").textContent=(text?text.split(/\s+/).length:0)+" words";$("stepsValue").textContent=$("steps").value;$("guidanceValue").textContent=Number($("guidance").value).toFixed(1);$("speedValue").textContent=Number($("speed").value).toFixed(2)+"?";$("quoteVoice").hidden=$("quote_mode").value!=="two_voice"}
function referenceView(quote, token, label){const audio=$(quote?"quoteAudio":"referenceAudio");audio.hidden=!token;if(token)audio.src="/reference/"+token;$(quote?"quoteStatus":"referenceStatus").textContent=label||(token?"Saved reference ready":"No reference selected")}
function fill(c){state=c;for(const key of fields){const el=$(key);if(el.type==="checkbox")el.checked=!!c[key];else el.value=c[key]??""}referenceView(false,c.reference);referenceView(true,c.quote_reference);update()}
async function task(button,fn){button.disabled=true;message("");try{await fn()}catch(e){message(e.message)}finally{button.disabled=false}}
async function save(){state=collect();await api("/api/config",state)}
async function upload(input,quote){const f=input.files[0];if(!f)return;await task(input,async()=>{if(f.size>30*1024*1024)throw Error("Use a file smaller than 30 MB.");const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(",")[1]);r.onerror=reject;r.readAsDataURL(f)});const ref=await api("/api/reference",{data});state[quote?"quote_reference":"reference"]=ref.id;referenceView(quote,ref.id,f.name+" ? "+ref.seconds+" seconds");message("Reference loaded. Make sure its transcript matches the recording.",true)})}
function showResult(result){$("resultCard").hidden=false;$("resultAudio").src=result.audio;$("download").href=result.audio;$("playerLink").href=result.player;$("reportLink").href=result.report;const passed=result.word_checks.filter(x=>x==="pass").length;$("resultInfo").textContent=(result.seconds/60).toFixed(2)+" minutes ? "+passed+"/"+result.word_checks.length+" phrases passed word checks";$("warnings").replaceChildren();for(const note of result.warnings){const li=document.createElement("li");li.textContent=note;$("warnings").append(li)}}
function progress(job){$("progressCard").hidden=false;$("progressCount").textContent=job.completed+" / "+job.total+" phrases";$("progress").max=job.total;$("progress").value=job.completed;$("log").textContent=job.log.join("\n");$("progressText").textContent=job.log.at(-1)||"Connecting to Colab?";$("progressTitle").textContent=job.state==="complete"?"Narration complete":job.state==="failed"?"Generation needs attention":"Creating your narration"}
async function poll(){if(!active)return;try{const job=await api("/api/job/"+active);progress(job);if(job.state==="complete"){showResult(job.result);active=null;$("generate").disabled=false;await loadHistory();return}if(job.state==="failed"){message(job.error+" Check the run log for details.");active=null;$("generate").disabled=false;await loadHistory();return}}catch(e){message("Status connection interrupted. Retrying? "+e.message)}setTimeout(poll,2000)}
async function loadHistory(){const jobs=await api("/api/jobs");$("historyList").replaceChildren();if(!jobs.length){$("historyList").textContent="Your generated narrations will appear here.";return}for(const job of jobs){const row=document.createElement("div");row.className="history-row";const name=document.createElement("span");name.textContent=job.id+" ? "+job.state;row.append(name);if(job.result){const button=document.createElement("button");button.className="quiet";button.textContent="Listen ?";button.onclick=()=>{showResult(job.result);$("resultCard").scrollIntoView({behavior:"smooth"})};row.append(button)}$("historyList").append(row);if(job.state==="running"&&!active){active=job.id;$("generate").disabled=true;poll()}}}
$("saveConnection").onclick=()=>task($("saveConnection"),async()=>{await save();$("connectionStatus").textContent="URL saved. New generations will use this endpoint."});
$("testConnection").onclick=()=>task($("testConnection"),async()=>{await save();$("connectionStatus").textContent="Connecting?";try{const r=await api("/api/connect",{endpoint:$("endpoint").value});const caps=r.capabilities;const extended=caps.normalize_text&&caps.seed;$("connectionStatus").textContent=extended?"Connected ? extended runtime with seeds and text normalization.":"Connected ? stock demo. Local word checks are available; endpoint seeds and numeral normalization are not.";$("connectionStatus").className="status success"}catch(e){$("connectionStatus").textContent="Connection failed. Check that Colab is running and the share URL is current.";$("connectionStatus").className="status error";throw e}});
$("saveSettings").onclick=()=>task($("saveSettings"),async()=>{await save();message("Settings saved on this computer.",true)});
$("loadSample").onclick=()=>task($("loadSample"),async()=>{const c=await api("/api/sample");$("passage").value=c.passage;$("format").value=c.format;update();message("Sample story loaded. Quote blocks are preserved.",true)});
$("previewPlan").onclick=()=>task($("previewPlan"),async()=>{const r=await api("/api/plan",collect());$("planDetails").hidden=false;$("planDetails").open=true;$("plan").replaceChildren();r.chunks.forEach((c,i)=>{const el=document.createElement("div");el.className="phrase";const meta=document.createElement("small");meta.textContent="Phrase "+(i+1)+" ? block "+c.block_index+" ? "+c.role+" ? "+c.pause_after_ms+" ms pause";const p=document.createElement("p");p.textContent=c.text;el.append(meta,p);$("plan").append(el)});message(r.chunks.length+" phrases planned. No inference was run.",true)});
$("generate").onclick=async()=>{const button=$("generate");button.disabled=true;message("");try{await save();const job=await api("/api/generate",collect());active=job.id;$("resultCard").hidden=true;$("progressCard").hidden=false;$("progressCard").scrollIntoView({behavior:"smooth"});poll()}catch(e){message(e.message);button.disabled=false}};
$("referenceFile").onchange=()=>upload($("referenceFile"),false);$("quoteFile").onchange=()=>upload($("quoteFile"),true);
$("refreshHistory").onclick=()=>task($("refreshHistory"),loadHistory);
for(const key of fields)$(key).addEventListener("input",update);
(async()=>{try{fill(await api("/api/config"));await loadHistory()}catch(e){message("Could not load Studio: "+e.message)}})();